[package]
name = "auth0_jwt"
version = "0.1.0"
edition = "2018"

[dependencies]
jwks-client = { git = "https://github.com/jfbilodeau/jwks-client", rev = "bc8ace0" }
chrono = "0.4"
thiserror = "1"
serde = { version = "1.0.*", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
